### ISSUE TITLE
添加或修改菜单后刷新页面报错

### ISSUE THREAD

**Issue by 5vbear** [uikoo9/jfinalQ#2]
可能是缓存的问题

**Comment by uikoo9** [comment]
贴一下错误信息

**Comment by 5vbear** [comment]
FreeMarker template error:
The following has evaluated to null or missing:
==> menu.submenus  [in template "WEB-INF/view/base/head/head.html" at line 23, column 78]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

## The failing instruction (FTL stack trace):

==> #if menu.submenus()?size gt 0  [in template "WEB-INF/view/base/head/head.html" in macro "bshead" at line 23, column 73]
    #list menus as menu  [in template "WEB-INF/view/base/head/head.html" in macro "bshead" at line 22, column 65]
    #if user??  [in template "WEB-INF/view/base/head/head.html" in macro "bshead" at line 19, column 41]
    @bshead  [in template "WEB-INF/view/base/inc.html" in macro "bsbody" at line 201, column 27]
    @bsbody qmask=qmask  [in template "WEB-INF/view/base/inc.html" in macro "html" at line 7, column 17]

##     @html  [in template "WEB-INF/view/base/common/manage.html" at line 3, column 1]

## Java stack trace (for programmers):

freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
    at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:98)
    at freemarker.core.UnexpectedTypeException.newDesciptionBuilder(UnexpectedTypeException.java:41)
    at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:24)
    at freemarker.core.MethodCall._eval(MethodCall.java:119)
    at freemarker.core.Expression.eval(Expression.java:111)
    at freemarker.core.MiscellaneousBuiltins$sizeBI._eval(MiscellaneousBuiltins.java:42)
    at freemarker.core.Expression.eval(Expression.java:111)
    at freemarker.core.EvalUtil.compare(EvalUtil.java:146)
    at freemarker.core.ComparisonExpression.evalToBoolean(ComparisonExpression.java:103)
    at freemarker.core.IfBlock.accept(IfBlock.java:82)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:181)
    at freemarker.core.Environment.visitIteratorBlock(Environment.java:509)
    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:103)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.IfBlock.accept(IfBlock.java:84)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.Macro$Context.runMacro(Macro.java:209)
    at freemarker.core.Environment.visit(Environment.java:694)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:116)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.Macro$Context.runMacro(Macro.java:209)
    at freemarker.core.Environment.visit(Environment.java:694)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:116)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.Macro$Context.runMacro(Macro.java:209)
    at freemarker.core.Environment.visit(Environment.java:694)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:116)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.Environment.process(Environment.java:243)
    at freemarker.template.Template.process(Template.java:277)
    at com.jfinal.render.FreeMarkerRender.render(FreeMarkerRender.java:145)
    at com.jfinal.core.ActionHandler.handle(ActionHandler.java:97)
    at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

一月 25, 2016 3:25:40 下午 com.jfinal.core.ActionHandler error
严重: /manage
com.jfinal.render.RenderException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> menu.submenus  [in template "WEB-INF/view/base/head/head.html" at line 23, column 78]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 5 more):
==> #if menu.submenus()?size gt 0  [in template "WEB-INF/view/base/head/head.html" in macro "bshead" at line 23, column 73]
    at com.jfinal.render.FreeMarkerRender.render(FreeMarkerRender.java:147)
    at com.jfinal.core.ActionHandler.handle(ActionHandler.java:97)
    at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> menu.submenus  [in template "WEB-INF/view/base/head/head.html" at line 23, column 78]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 5 more):
==> #if menu.submenus()?size gt 0  [in template "WEB-INF/view/base/head/head.html" in macro "bshead" at line 23, column 73]
    at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:98)
    at freemarker.core.UnexpectedTypeException.newDesciptionBuilder(UnexpectedTypeException.java:41)
    at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:24)
    at freemarker.core.MethodCall._eval(MethodCall.java:119)
    at freemarker.core.Expression.eval(Expression.java:111)
    at freemarker.core.MiscellaneousBuiltins$sizeBI._eval(MiscellaneousBuiltins.java:42)
    at freemarker.core.Expression.eval(Expression.java:111)
    at freemarker.core.EvalUtil.compare(EvalUtil.java:146)
    at freemarker.core.ComparisonExpression.evalToBoolean(ComparisonExpression.java:103)
    at freemarker.core.IfBlock.accept(IfBlock.java:82)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:181)
    at freemarker.core.Environment.visitIteratorBlock(Environment.java:509)
    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:103)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.IfBlock.accept(IfBlock.java:84)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.Macro$Context.runMacro(Macro.java:209)
    at freemarker.core.Environment.visit(Environment.java:694)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:116)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.Macro$Context.runMacro(Macro.java:209)
    at freemarker.core.Environment.visit(Environment.java:694)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:116)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.Macro$Context.runMacro(Macro.java:209)
    at freemarker.core.Environment.visit(Environment.java:694)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:116)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.MixedContent.accept(MixedContent.java:93)
    at freemarker.core.Environment.visit(Environment.java:265)
    at freemarker.core.Environment.process(Environment.java:243)
    at freemarker.template.Template.process(Template.java:277)
    at com.jfinal.render.FreeMarkerRender.render(FreeMarkerRender.java:145)
    ... 19 more
